super_people/config/routes.rb
Rails.application.routes.draw do
  root 'super_people#index'
  resources :abilities
  resources :super_people
  get '/villians', to: 'super_people#villians', as: :villians
  get '/heroes', to: 'super_people#heroes', as: :heroes

end

super_people/app/models/ability.rb
class Ability < ActiveRecord::Base
end

super_people/app/models/super_person.rb
class SuperPerson < ActiveRecord::Base
end

super_people/app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def index
  	@ability = Ability.all
  end

  def show
  	@ability = Ability.find(params[:id])
    @super_person = SuperPerson.find(params[:id])
  end

  def new
  	@ability = Ability.new
  end

  def create
  	@ability = Ability.new(ability_params)

  	if @ability.save
  	  redirect_to abilities_path
  	else
  	  render.new
  	end
  end

  def edit
    @ability = Ability.find(params[:id])
  end

  def update
    @ability = Ability.find(params[:id])

    if @abilities.update(ability_params)
      redirect_to abilities_path
    else
      render :edit
    end
  end

  def destroy
    @ability = Ability.find(params[:id])
    @ability.destroy
    redirect_to abilities_path
  end

  def delete
  end

  private

  def ability_params
    params.require(:ability).permit(:name, :super_id, :description)
  end

end

super_people/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

super_people/app/controllers/super_people_controller.rb
class SuperPeopleController < ApplicationController
  def index
    @super_person = SuperPerson.all
  end

  def show
    @super_person = SuperPerson.find(params[:id])
  end

  def new
    @super_person = SuperPerson.new
  end

  def create
    @super_person = SuperPerson.new(super_person_params)

    if @super_person.save
      redirect_to super_people_path
    else
      render.new
    end
  end


  def edit
    @super_person = SuperPerson.find(params[:id])
  end

  def update
    @super_person = SuperPerson.find(params[:id])

    if @super_person.find_by(super_person_params)
      redirect_to super_people_path
    else
      render :edit
    end
  end

  def destroy
    @super_person = SuperPerson.find(params[:id])
    @super_person.destroy
    redirect_to super_people_path
  end

  def delete
  end

  def villians
    @super_person = SuperPerson.where(is_hero: false)
  end

  def heroes
    @super_person = SuperPerson.where(is_hero: true)
  end


  private

  def super_person_params
    params.require(:super_person).permit(:name, :gender, :nemesis_id, :has_cape, :location, :weakness, :is_hero, :description)
  end

end

super_people/app/helpers/abilities_helper.rb
module AbilitiesHelper
end

super_people/app/helpers/application_helper.rb
module ApplicationHelper
end

super_people/app/helpers/super_people_helper.rb
module SuperPeopleHelper
end

super_people/app/views/abilities/_form.html.erb
<%= form_for @ability do |x| %>
  <%= x.label :name %>: 
  <%= x.text_field :name %>

  <%= x.label :super_with_ability_id %>: 
  <%= x.collection_select(:name, SuperPerson.all, :id, :name) %>

  <%= x.label :description %>
  <%= x.text_field :description %>


  <%= x.submit %>
<% end %>

super_people/app/views/abilities/edit.html.erb
<h1>Edit Ability</h1>
<%= render 'form' %>

super_people/app/views/abilities/index.html.erb
<!-- <p>Find me in app/views/ability/index.html.erb</p> -->

<h1> Abilities </h1>
<p><%= link_to 'New Ability', new_ability_path %></p>


<% @ability.each do |ability| %>
  <h2><%= ability.name %></h2>
  <%= link_to 'Show', ability_path(ability) %>
<% end %>

super_people/app/views/abilities/new.html.erb
<!-- <p>Find me in app/views/abilities/new.html.erb</p> -->

<h1> New Ability </h1>
<%= render 'form' %>

super_people/app/views/abilities/show.html.erb
<h1>Ability Show</h1>


  <h2><%= @ability.name %></h2>
  <p><%= @super_person.name %></p>
  <p><%= @ability.description %></p>
  <%= link_to 'Edit', edit_ability_path %>
  <%= link_to 'Destroy', @ability, method: :delete %>

super_people/app/views/layouts/_navbar.html.erb
<!-- Supers, Abilites, Villians, Super Heroes  -->

<%= link_to 'Supers', root_path %> |
<%= link_to 'Abilities', abilities_path %> |
<%= link_to 'Villians', villians_path %> |
<%= link_to 'Super Heroes', heroes_path %>

super_people/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

super_people/app/views/super_people/_form.html.erb
<%= form_for @super_person do |x| %>
  <%= x.label :name %>: 
  <%= x.text_field :name %><br>

  <%= x.label :gender %>: 
  <%= x.select :gender, options_for_select([['Female', true], ['Male', false]])%><br>

  <%= x.label :nemesis_id %>:
  <%= x.collection_select(:name, SuperPerson.all, :id, :name) %><br>

  <%= x.label :has_cape %>:
  <%= x.select :has_cape, options_for_select([['Yes', true], ['No', false]])%><br>

  <%= x.label :location %>:
  <%= x.text_field :location %><br>

  <%= x.label :weakness %>:
  <%= x.text_field :weakness %><br>

  <%= x.label :is_hero %>:
  <%= x.select :is_hero, options_for_select([['Yes', true], ['No', false]])%><br>

  <%= x.label :description %>:
  <%= x.text_field :description %><br>

  <%= x.submit %>
<% end %>

super_people/app/views/super_people/edit.html.erb
<h1>Edit Super</h1>
<%= render 'form' %>

super_people/app/views/super_people/heroes.html.erb
<h1>Super Heroes</h1>
<p><%= link_to 'New Hero', new_super_person_path %></p> 

<% @super_person.each do |super_person| %>
  <h2><%= super_person.name %></h2>
  <%= link_to 'Show', super_person_path(super_person) %>
<% end %>

super_people/app/views/super_people/index.html.erb
<!-- <p>Find me in app/views/super_humans/index.html.erb</p> -->

<h1> Supers </h1> 

<p><%= link_to 'New Super', new_super_person_path %></p> 
<!--TODO: update link_to new path -->

<% @super_person.each do |super_person| %>
  <h2><%= super_person.name %></h2>
  <%= link_to 'Show', super_person_path(super_person) %>
<% end %>

super_people/app/views/super_people/new.html.erb
<h1> New Super </h1>
<%= render 'form' %>

super_people/app/views/super_people/show.html.erb
<h1>Super Profile</h1>

  <h2>Name:  <%= @super_person.name %></h2>

  <p>Gender: <%= @super_person.gender ? "Female" : "Male"%></p>

  <p>Nemesis: <%= @super_person.nemesis_id %></p>
  
  <p>Has Cape: <%= @super_person.has_cape ? "Yes" : "No"%></p>
  
  <p>Location: <%= @super_person.location %></p>
  
  <p>Weakness: <%= @super_person.weakness %></p>
  
  <p>Is: <%= @super_person.is_hero ? "Hero" : "Villian" %></p>
  
  <p>Desc: <%= @super_person.description %></p>
  
  <%= link_to 'Edit Super', edit_super_person_path %>
  <%= link_to 'Destroy Super', @super_person, method: :delete %>

super_people/app/views/super_people/villians.html.erb
<h1>Villians</h1>

<% @super_person.each do |super_person| %>
  <h2><%= super_person.name %></h2>
  <%= link_to 'Show', super_person_path(super_person) %>
<% end %>